apiVersion: apps/v1
kind: Deployment
metadata:
 name: guestbook-v1
spec:
 replicas: 2
 template:
   metadata:
     labels:
       app: guestbook-v1
   spec:
     containers:
     - name: guestbook-v1
       image: ibmcom/guestbook:v1
       # for local development against minikube registry
       #imagePullPolicy: Never
       ports:
        - name: http-server
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: guestbook-v1service
 labels:
   app: guestbook-v1service
spec:
 type: NodePort
 ports:
   # the port that this service should serve on
   - port: 80
 # label keys and values that must match in order to receive traffic for this service
 selector:
   app: guestbook-v1
   validate:=false
  